defmodule Chatter.Repo.Migrations.AddRoomsAndMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:rooms, primary_key: false) do
      add :owner_id,
          references(:users,
            column: :id,
            name: "rooms_owner_id_fkey",
            type: :uuid,
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :created_at, :utc_datetime_usec, null: false
      add :name, :text, null: false
      add :id, :bigserial, null: false, primary_key: true
    end

    create table(:messages, primary_key: false) do
      add :author_id,
          references(:users, column: :id, name: "messages_author_id_fkey", type: :uuid),
          null: false

      add :room_id, references(:rooms, column: :id, name: "messages_room_id_fkey", type: :bigint)
      add :updated_at, :utc_datetime_usec, null: false
      add :created_at, :utc_datetime_usec, null: false
      add :content, :text, null: false
      add :id, :bigserial, null: false, primary_key: true
    end
  end

  def down do
    drop constraint(:messages, "messages_room_id_fkey")

    drop constraint(:messages, "messages_author_id_fkey")

    drop table(:messages)

    drop constraint(:rooms, "rooms_owner_id_fkey")

    drop table(:rooms)
  end
end
